AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create an EC2 instance with a security group that allows SSH access'
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
    ImageId: ami-0c11a84584d4e09dd
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref InstanceSecurityGroup
  MyVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 10
      AvailabilityZone: !GetAtt MyInstance.AvailabilityZone
  MyVolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref MyInstance
      VolumeId: !Ref MyVolume
      Device: /dev/sdf